//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VATDesktop.Repo.SalesInvoiceExpWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesInvoiceExpWCF.ISalesInvoiceExpWCF")]
    public interface ISalesInvoiceExpWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/DoWork", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/DoWork", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/SelectAllList", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/SelectAllListResponse")]
        string SelectAllList(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/SelectAllList", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/SelectAllListResponse")]
        System.Threading.Tasks.Task<string> SelectAllListAsync(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/Delete", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/DeleteResponse")]
        string Delete(string vmwcf, string idswcf, string connVMWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/Delete", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(string vmwcf, string idswcf, string connVMWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/InsertToSalesInvoiceExp", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/InsertToSalesInvoiceExpResponse")]
        string InsertToSalesInvoiceExp(string vmwcf, string connVMWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/InsertToSalesInvoiceExp", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/InsertToSalesInvoiceExpResponse")]
        System.Threading.Tasks.Task<string> InsertToSalesInvoiceExpAsync(string vmwcf, string connVMWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/SelectAll", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/SelectAllResponse")]
        string SelectAll(int ID, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/SelectAll", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/SelectAllResponse")]
        System.Threading.Tasks.Task<string> SelectAllAsync(int ID, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/UpdateSalesInvoiceExps", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/UpdateSalesInvoiceExpsResponse")]
        string UpdateSalesInvoiceExps(string vmwcf, string connVMWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesInvoiceExpWCF/UpdateSalesInvoiceExps", ReplyAction="http://tempuri.org/ISalesInvoiceExpWCF/UpdateSalesInvoiceExpsResponse")]
        System.Threading.Tasks.Task<string> UpdateSalesInvoiceExpsAsync(string vmwcf, string connVMWCF);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesInvoiceExpWCFChannel : VATDesktop.Repo.SalesInvoiceExpWCF.ISalesInvoiceExpWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesInvoiceExpWCFClient : System.ServiceModel.ClientBase<VATDesktop.Repo.SalesInvoiceExpWCF.ISalesInvoiceExpWCF>, VATDesktop.Repo.SalesInvoiceExpWCF.ISalesInvoiceExpWCF {
        
        public SalesInvoiceExpWCFClient() {
        }
        
        public SalesInvoiceExpWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesInvoiceExpWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesInvoiceExpWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesInvoiceExpWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string SelectAllList(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMWCF) {
            return base.Channel.SelectAllList(Id, conditionFieldswcf, conditionValueswcf, connVMWCF);
        }
        
        public System.Threading.Tasks.Task<string> SelectAllListAsync(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMWCF) {
            return base.Channel.SelectAllListAsync(Id, conditionFieldswcf, conditionValueswcf, connVMWCF);
        }
        
        public string Delete(string vmwcf, string idswcf, string connVMWCF) {
            return base.Channel.Delete(vmwcf, idswcf, connVMWCF);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(string vmwcf, string idswcf, string connVMWCF) {
            return base.Channel.DeleteAsync(vmwcf, idswcf, connVMWCF);
        }
        
        public string InsertToSalesInvoiceExp(string vmwcf, string connVMWCF) {
            return base.Channel.InsertToSalesInvoiceExp(vmwcf, connVMWCF);
        }
        
        public System.Threading.Tasks.Task<string> InsertToSalesInvoiceExpAsync(string vmwcf, string connVMWCF) {
            return base.Channel.InsertToSalesInvoiceExpAsync(vmwcf, connVMWCF);
        }
        
        public string SelectAll(int ID, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMWCF) {
            return base.Channel.SelectAll(ID, conditionFieldswcf, conditionValueswcf, Dt, connVMWCF);
        }
        
        public System.Threading.Tasks.Task<string> SelectAllAsync(int ID, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMWCF) {
            return base.Channel.SelectAllAsync(ID, conditionFieldswcf, conditionValueswcf, Dt, connVMWCF);
        }
        
        public string UpdateSalesInvoiceExps(string vmwcf, string connVMWCF) {
            return base.Channel.UpdateSalesInvoiceExps(vmwcf, connVMWCF);
        }
        
        public System.Threading.Tasks.Task<string> UpdateSalesInvoiceExpsAsync(string vmwcf, string connVMWCF) {
            return base.Channel.UpdateSalesInvoiceExpsAsync(vmwcf, connVMWCF);
        }
    }
}
