//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VATServer.Library.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ivaspxapp1:55000/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
            "C_SOAP_BIDA_TO_IVAS&receiverParty=&receiverService=&interface=SI_RET_SENDER&inte" +
            "rfaceNamespace=http%3A%2F%2Fnbr.gov.bd%2Fregist91")]
        public string VATServer_Library_NBRWebService_SI_RET_SENDERService {
            get {
                return ((string)(this["VATServer_Library_NBRWebService_SI_RET_SENDERService"]));
            }
        }
    }
}
