//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VATDesktop.Repo.BankInformationWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankInformationWCF.IBankInformationWCF")]
    public interface IBankInformationWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/DoWork", ReplyAction="http://tempuri.org/IBankInformationWCF/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/DoWork", ReplyAction="http://tempuri.org/IBankInformationWCF/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/InsertToBankInformation", ReplyAction="http://tempuri.org/IBankInformationWCF/InsertToBankInformationResponse")]
        string InsertToBankInformation(string vmwcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/InsertToBankInformation", ReplyAction="http://tempuri.org/IBankInformationWCF/InsertToBankInformationResponse")]
        System.Threading.Tasks.Task<string> InsertToBankInformationAsync(string vmwcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/UpdateBankInformation", ReplyAction="http://tempuri.org/IBankInformationWCF/UpdateBankInformationResponse")]
        string UpdateBankInformation(string vmwcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/UpdateBankInformation", ReplyAction="http://tempuri.org/IBankInformationWCF/UpdateBankInformationResponse")]
        System.Threading.Tasks.Task<string> UpdateBankInformationAsync(string vmwcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/Delete", ReplyAction="http://tempuri.org/IBankInformationWCF/DeleteResponse")]
        string Delete(string vmwcf, string idswcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/Delete", ReplyAction="http://tempuri.org/IBankInformationWCF/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(string vmwcf, string idswcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/SelectAll", ReplyAction="http://tempuri.org/IBankInformationWCF/SelectAllResponse")]
        string SelectAll(int Id, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/SelectAll", ReplyAction="http://tempuri.org/IBankInformationWCF/SelectAllResponse")]
        System.Threading.Tasks.Task<string> SelectAllAsync(int Id, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/GetExcelData", ReplyAction="http://tempuri.org/IBankInformationWCF/GetExcelDataResponse")]
        string GetExcelData(string idswcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/GetExcelData", ReplyAction="http://tempuri.org/IBankInformationWCF/GetExcelDataResponse")]
        System.Threading.Tasks.Task<string> GetExcelDataAsync(string idswcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/DropDownAll", ReplyAction="http://tempuri.org/IBankInformationWCF/DropDownAllResponse")]
        string DropDownAll(string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/DropDownAll", ReplyAction="http://tempuri.org/IBankInformationWCF/DropDownAllResponse")]
        System.Threading.Tasks.Task<string> DropDownAllAsync(string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/DropDown", ReplyAction="http://tempuri.org/IBankInformationWCF/DropDownResponse")]
        string DropDown(string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/DropDown", ReplyAction="http://tempuri.org/IBankInformationWCF/DropDownResponse")]
        System.Threading.Tasks.Task<string> DropDownAsync(string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/SelectAllList", ReplyAction="http://tempuri.org/IBankInformationWCF/SelectAllListResponse")]
        string SelectAllList(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankInformationWCF/SelectAllList", ReplyAction="http://tempuri.org/IBankInformationWCF/SelectAllListResponse")]
        System.Threading.Tasks.Task<string> SelectAllListAsync(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMwcf);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankInformationWCFChannel : VATDesktop.Repo.BankInformationWCF.IBankInformationWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankInformationWCFClient : System.ServiceModel.ClientBase<VATDesktop.Repo.BankInformationWCF.IBankInformationWCF>, VATDesktop.Repo.BankInformationWCF.IBankInformationWCF {
        
        public BankInformationWCFClient() {
        }
        
        public BankInformationWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankInformationWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankInformationWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankInformationWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string InsertToBankInformation(string vmwcf, string connVMwcf) {
            return base.Channel.InsertToBankInformation(vmwcf, connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> InsertToBankInformationAsync(string vmwcf, string connVMwcf) {
            return base.Channel.InsertToBankInformationAsync(vmwcf, connVMwcf);
        }
        
        public string UpdateBankInformation(string vmwcf, string connVMwcf) {
            return base.Channel.UpdateBankInformation(vmwcf, connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> UpdateBankInformationAsync(string vmwcf, string connVMwcf) {
            return base.Channel.UpdateBankInformationAsync(vmwcf, connVMwcf);
        }
        
        public string Delete(string vmwcf, string idswcf, string connVMwcf) {
            return base.Channel.Delete(vmwcf, idswcf, connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(string vmwcf, string idswcf, string connVMwcf) {
            return base.Channel.DeleteAsync(vmwcf, idswcf, connVMwcf);
        }
        
        public string SelectAll(int Id, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMwcf) {
            return base.Channel.SelectAll(Id, conditionFieldswcf, conditionValueswcf, Dt, connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> SelectAllAsync(int Id, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMwcf) {
            return base.Channel.SelectAllAsync(Id, conditionFieldswcf, conditionValueswcf, Dt, connVMwcf);
        }
        
        public string GetExcelData(string idswcf, string connVMwcf) {
            return base.Channel.GetExcelData(idswcf, connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> GetExcelDataAsync(string idswcf, string connVMwcf) {
            return base.Channel.GetExcelDataAsync(idswcf, connVMwcf);
        }
        
        public string DropDownAll(string connVMwcf) {
            return base.Channel.DropDownAll(connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> DropDownAllAsync(string connVMwcf) {
            return base.Channel.DropDownAllAsync(connVMwcf);
        }
        
        public string DropDown(string connVMwcf) {
            return base.Channel.DropDown(connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> DropDownAsync(string connVMwcf) {
            return base.Channel.DropDownAsync(connVMwcf);
        }
        
        public string SelectAllList(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMwcf) {
            return base.Channel.SelectAllList(Id, conditionFieldswcf, conditionValueswcf, connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> SelectAllListAsync(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMwcf) {
            return base.Channel.SelectAllListAsync(Id, conditionFieldswcf, conditionValueswcf, connVMwcf);
        }
    }
}
