//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VATDesktop.Repo.VendorGroupWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VendorGroupWCF.IVendorGroupWCF")]
    public interface IVendorGroupWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/DoWork", ReplyAction="http://tempuri.org/IVendorGroupWCF/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/DoWork", ReplyAction="http://tempuri.org/IVendorGroupWCF/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/InsertToVendorGroup", ReplyAction="http://tempuri.org/IVendorGroupWCF/InsertToVendorGroupResponse")]
        string InsertToVendorGroup(string vmwcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/InsertToVendorGroup", ReplyAction="http://tempuri.org/IVendorGroupWCF/InsertToVendorGroupResponse")]
        System.Threading.Tasks.Task<string> InsertToVendorGroupAsync(string vmwcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/UpdateToVendorGroup", ReplyAction="http://tempuri.org/IVendorGroupWCF/UpdateToVendorGroupResponse")]
        string UpdateToVendorGroup(string vmwcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/UpdateToVendorGroup", ReplyAction="http://tempuri.org/IVendorGroupWCF/UpdateToVendorGroupResponse")]
        System.Threading.Tasks.Task<string> UpdateToVendorGroupAsync(string vmwcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/DropDownAll", ReplyAction="http://tempuri.org/IVendorGroupWCF/DropDownAllResponse")]
        string DropDownAll(string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/DropDownAll", ReplyAction="http://tempuri.org/IVendorGroupWCF/DropDownAllResponse")]
        System.Threading.Tasks.Task<string> DropDownAllAsync(string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/DropDown", ReplyAction="http://tempuri.org/IVendorGroupWCF/DropDownResponse")]
        string DropDown(string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/DropDown", ReplyAction="http://tempuri.org/IVendorGroupWCF/DropDownResponse")]
        System.Threading.Tasks.Task<string> DropDownAsync(string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/SelectAll", ReplyAction="http://tempuri.org/IVendorGroupWCF/SelectAllResponse")]
        string SelectAll(int Id, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/SelectAll", ReplyAction="http://tempuri.org/IVendorGroupWCF/SelectAllResponse")]
        System.Threading.Tasks.Task<string> SelectAllAsync(int Id, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/SelectAllList", ReplyAction="http://tempuri.org/IVendorGroupWCF/SelectAllListResponse")]
        string SelectAllList(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/SelectAllList", ReplyAction="http://tempuri.org/IVendorGroupWCF/SelectAllListResponse")]
        System.Threading.Tasks.Task<string> SelectAllListAsync(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/Delete", ReplyAction="http://tempuri.org/IVendorGroupWCF/DeleteResponse")]
        string Delete(string vmwcf, string idswcf, string connVMwcf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorGroupWCF/Delete", ReplyAction="http://tempuri.org/IVendorGroupWCF/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(string vmwcf, string idswcf, string connVMwcf);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVendorGroupWCFChannel : VATDesktop.Repo.VendorGroupWCF.IVendorGroupWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendorGroupWCFClient : System.ServiceModel.ClientBase<VATDesktop.Repo.VendorGroupWCF.IVendorGroupWCF>, VATDesktop.Repo.VendorGroupWCF.IVendorGroupWCF {
        
        public VendorGroupWCFClient() {
        }
        
        public VendorGroupWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendorGroupWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendorGroupWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendorGroupWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string InsertToVendorGroup(string vmwcf, string connVMwcf) {
            return base.Channel.InsertToVendorGroup(vmwcf, connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> InsertToVendorGroupAsync(string vmwcf, string connVMwcf) {
            return base.Channel.InsertToVendorGroupAsync(vmwcf, connVMwcf);
        }
        
        public string UpdateToVendorGroup(string vmwcf, string connVMwcf) {
            return base.Channel.UpdateToVendorGroup(vmwcf, connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> UpdateToVendorGroupAsync(string vmwcf, string connVMwcf) {
            return base.Channel.UpdateToVendorGroupAsync(vmwcf, connVMwcf);
        }
        
        public string DropDownAll(string connVMwcf) {
            return base.Channel.DropDownAll(connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> DropDownAllAsync(string connVMwcf) {
            return base.Channel.DropDownAllAsync(connVMwcf);
        }
        
        public string DropDown(string connVMwcf) {
            return base.Channel.DropDown(connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> DropDownAsync(string connVMwcf) {
            return base.Channel.DropDownAsync(connVMwcf);
        }
        
        public string SelectAll(int Id, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMwcf) {
            return base.Channel.SelectAll(Id, conditionFieldswcf, conditionValueswcf, Dt, connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> SelectAllAsync(int Id, string conditionFieldswcf, string conditionValueswcf, bool Dt, string connVMwcf) {
            return base.Channel.SelectAllAsync(Id, conditionFieldswcf, conditionValueswcf, Dt, connVMwcf);
        }
        
        public string SelectAllList(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMwcf) {
            return base.Channel.SelectAllList(Id, conditionFieldswcf, conditionValueswcf, connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> SelectAllListAsync(int Id, string conditionFieldswcf, string conditionValueswcf, string connVMwcf) {
            return base.Channel.SelectAllListAsync(Id, conditionFieldswcf, conditionValueswcf, connVMwcf);
        }
        
        public string Delete(string vmwcf, string idswcf, string connVMwcf) {
            return base.Channel.Delete(vmwcf, idswcf, connVMwcf);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(string vmwcf, string idswcf, string connVMwcf) {
            return base.Channel.DeleteAsync(vmwcf, idswcf, connVMwcf);
        }
    }
}
