//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VATServer.Library.NBRWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_RET_SENDERBinding", Namespace="http://nbr.gov.bd/regist91")]
    public partial class SI_RET_SENDERService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_RET_SENDEROperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_RET_SENDERService() {
            this.Url = global::VATServer.Library.Properties.Settings.Default.VATServer_Library_NBRWebService_SI_RET_SENDERService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_RET_SENDERCompletedEventHandler SI_RET_SENDERCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_RET_SENDER([System.Xml.Serialization.XmlElementAttribute(Namespace="http://nbr.gov.bd/regist91")] DT_RET_MSG_REQ_91 MT_RET_MSG_REQ) {
            this.Invoke("SI_RET_SENDER", new object[] {
                        MT_RET_MSG_REQ});
        }
        
        /// <remarks/>
        public void SI_RET_SENDERAsync(DT_RET_MSG_REQ_91 MT_RET_MSG_REQ) {
            this.SI_RET_SENDERAsync(MT_RET_MSG_REQ, null);
        }
        
        /// <remarks/>
        public void SI_RET_SENDERAsync(DT_RET_MSG_REQ_91 MT_RET_MSG_REQ, object userState) {
            if ((this.SI_RET_SENDEROperationCompleted == null)) {
                this.SI_RET_SENDEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_RET_SENDEROperationCompleted);
            }
            this.InvokeAsync("SI_RET_SENDER", new object[] {
                        MT_RET_MSG_REQ}, this.SI_RET_SENDEROperationCompleted, userState);
        }
        
        private void OnSI_RET_SENDEROperationCompleted(object arg) {
            if ((this.SI_RET_SENDERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_RET_SENDERCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_MSG_REQ_91 {
        
        private DT_RET_MSG_HEADER i_MSG_HDRField;
        
        private DT_RET_PI_XML_DATA_MF i_MAIN_FORMField;
        
        private DT_RET_MSG_REQ_91IT_SUBF_GOSERV iT_SUBF_GOSERVField;
        
        private DT_RET_MSG_REQ_91IT_SUBF_VDS iT_SUBF_VDSField;
        
        private DT_RET_MSG_REQ_91IT_SUBF_BOE iT_SUBF_BOEField;
        
        private DT_RET_MSG_REQ_91IT_SUBF_CHALLAN iT_SUBF_CHALLANField;
        
        private DT_RET_MSG_REQ_91IT_SUBF_ATTACH iT_SUBF_ATTACHField;
        
        private DT_RET_MSG_REQ_91ATTACH_DOCUMENT aTTACH_DOCUMENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_MSG_HEADER I_MSG_HDR {
            get {
                return this.i_MSG_HDRField;
            }
            set {
                this.i_MSG_HDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_PI_XML_DATA_MF I_MAIN_FORM {
            get {
                return this.i_MAIN_FORMField;
            }
            set {
                this.i_MAIN_FORMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_MSG_REQ_91IT_SUBF_GOSERV IT_SUBF_GOSERV {
            get {
                return this.iT_SUBF_GOSERVField;
            }
            set {
                this.iT_SUBF_GOSERVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_MSG_REQ_91IT_SUBF_VDS IT_SUBF_VDS {
            get {
                return this.iT_SUBF_VDSField;
            }
            set {
                this.iT_SUBF_VDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_MSG_REQ_91IT_SUBF_BOE IT_SUBF_BOE {
            get {
                return this.iT_SUBF_BOEField;
            }
            set {
                this.iT_SUBF_BOEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_MSG_REQ_91IT_SUBF_CHALLAN IT_SUBF_CHALLAN {
            get {
                return this.iT_SUBF_CHALLANField;
            }
            set {
                this.iT_SUBF_CHALLANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_MSG_REQ_91IT_SUBF_ATTACH IT_SUBF_ATTACH {
            get {
                return this.iT_SUBF_ATTACHField;
            }
            set {
                this.iT_SUBF_ATTACHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_MSG_REQ_91ATTACH_DOCUMENT ATTACH_DOCUMENT {
            get {
                return this.aTTACH_DOCUMENTField;
            }
            set {
                this.aTTACH_DOCUMENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_MSG_HEADER {
        
        private string mSGIDField;
        
        private string tRANS_CODEField;
        
        private string sEND_DATEField;
        
        private string sEND_TIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANS_CODE {
            get {
                return this.tRANS_CODEField;
            }
            set {
                this.tRANS_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEND_DATE {
            get {
                return this.sEND_DATEField;
            }
            set {
                this.sEND_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEND_TIME {
            get {
                return this.sEND_TIMEField;
            }
            set {
                this.sEND_TIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_ATTACH_DOCUMENT {
        
        private string fILENAMEField;
        
        private string cONTENTField;
        
        private string fILETYPEField;
        
        private string dOCTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILENAME {
            get {
                return this.fILENAMEField;
            }
            set {
                this.fILENAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTENT {
            get {
                return this.cONTENTField;
            }
            set {
                this.cONTENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILETYPE {
            get {
                return this.fILETYPEField;
            }
            set {
                this.fILETYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOCTYPE {
            get {
                return this.dOCTYPEField;
            }
            set {
                this.dOCTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_SUBF_ATTACH {
        
        private string aTT_DOCTYPEField;
        
        private string tEXTField;
        
        private string nOTESField;
        
        private string cHKBOXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATT_DOCTYPE {
            get {
                return this.aTT_DOCTYPEField;
            }
            set {
                this.aTT_DOCTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT {
            get {
                return this.tEXTField;
            }
            set {
                this.tEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOTES {
            get {
                return this.nOTESField;
            }
            set {
                this.nOTESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHKBOX {
            get {
                return this.cHKBOXField;
            }
            set {
                this.cHKBOXField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_SUBF_CHALLAN {
        
        private string fIELD_IDField;
        
        private string cHALL_NOField;
        
        private string cHALL_DATEField;
        
        private string aCCOUNT_CODEField;
        
        private string cHAN_AMTField;
        
        private string nOTESField;
        
        private string bANCDField;
        
        private string bANKLField;
        
        private string a_NAMEOFBANKField;
        
        private string a_BRANCHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FIELD_ID {
            get {
                return this.fIELD_IDField;
            }
            set {
                this.fIELD_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHALL_NO {
            get {
                return this.cHALL_NOField;
            }
            set {
                this.cHALL_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHALL_DATE {
            get {
                return this.cHALL_DATEField;
            }
            set {
                this.cHALL_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_CODE {
            get {
                return this.aCCOUNT_CODEField;
            }
            set {
                this.aCCOUNT_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHAN_AMT {
            get {
                return this.cHAN_AMTField;
            }
            set {
                this.cHAN_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOTES {
            get {
                return this.nOTESField;
            }
            set {
                this.nOTESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANCD {
            get {
                return this.bANCDField;
            }
            set {
                this.bANCDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANKL {
            get {
                return this.bANKLField;
            }
            set {
                this.bANKLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_NAMEOFBANK {
            get {
                return this.a_NAMEOFBANKField;
            }
            set {
                this.a_NAMEOFBANKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_BRANCH {
            get {
                return this.a_BRANCHField;
            }
            set {
                this.a_BRANCHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_SUBF_BOE {
        
        private string fIELD_IDField;
        
        private string bOEField;
        
        private string bOE_DATEField;
        
        private string cUS_STATIONField;
        
        private string aTV_AMOUNTField;
        
        private string nOTESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FIELD_ID {
            get {
                return this.fIELD_IDField;
            }
            set {
                this.fIELD_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BOE {
            get {
                return this.bOEField;
            }
            set {
                this.bOEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BOE_DATE {
            get {
                return this.bOE_DATEField;
            }
            set {
                this.bOE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CUS_STATION {
            get {
                return this.cUS_STATIONField;
            }
            set {
                this.cUS_STATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATV_AMOUNT {
            get {
                return this.aTV_AMOUNTField;
            }
            set {
                this.aTV_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOTES {
            get {
                return this.nOTESField;
            }
            set {
                this.nOTESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_SUBF_VDS {
        
        private string fIELD_IDField;
        
        private string bINField;
        
        private string nAMEField;
        
        private string aDDRESSField;
        
        private string vALUEField;
        
        private string dEDUCT_VATField;
        
        private string iNVOICE_NOField;
        
        private string iNVOICE_DATEField;
        
        private string cERT_NOField;
        
        private string cERT_DATEField;
        
        private string aCCOUNT_CODEField;
        
        private string dEPOSIT_NOField;
        
        private string dEPOSIT_DATEField;
        
        private string nOTEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FIELD_ID {
            get {
                return this.fIELD_IDField;
            }
            set {
                this.fIELD_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIN {
            get {
                return this.bINField;
            }
            set {
                this.bINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESS {
            get {
                return this.aDDRESSField;
            }
            set {
                this.aDDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEDUCT_VAT {
            get {
                return this.dEDUCT_VATField;
            }
            set {
                this.dEDUCT_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INVOICE_NO {
            get {
                return this.iNVOICE_NOField;
            }
            set {
                this.iNVOICE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INVOICE_DATE {
            get {
                return this.iNVOICE_DATEField;
            }
            set {
                this.iNVOICE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CERT_NO {
            get {
                return this.cERT_NOField;
            }
            set {
                this.cERT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CERT_DATE {
            get {
                return this.cERT_DATEField;
            }
            set {
                this.cERT_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_CODE {
            get {
                return this.aCCOUNT_CODEField;
            }
            set {
                this.aCCOUNT_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEPOSIT_NO {
            get {
                return this.dEPOSIT_NOField;
            }
            set {
                this.dEPOSIT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEPOSIT_DATE {
            get {
                return this.dEPOSIT_DATEField;
            }
            set {
                this.dEPOSIT_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOTE {
            get {
                return this.nOTEField;
            }
            set {
                this.nOTEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_TBF_GOSERV {
        
        private string fIELD_IDField;
        
        private string gOOD_SERVICEField;
        
        private string vALUEField;
        
        private string sdField;
        
        private string vATField;
        
        private string dESCRIPTIONField;
        
        private string nOTESField;
        
        private string qUANTITYField;
        
        private string aCT_SALE_VALUEField;
        
        private string uNITField;
        
        private string iTEM_IDField;
        
        private string nAMEField;
        
        private string cATEGORYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FIELD_ID {
            get {
                return this.fIELD_IDField;
            }
            set {
                this.fIELD_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GOOD_SERVICE {
            get {
                return this.gOOD_SERVICEField;
            }
            set {
                this.gOOD_SERVICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SD {
            get {
                return this.sdField;
            }
            set {
                this.sdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VAT {
            get {
                return this.vATField;
            }
            set {
                this.vATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOTES {
            get {
                return this.nOTESField;
            }
            set {
                this.nOTESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACT_SALE_VALUE {
            get {
                return this.aCT_SALE_VALUEField;
            }
            set {
                this.aCT_SALE_VALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEM_ID {
            get {
                return this.iTEM_IDField;
            }
            set {
                this.iTEM_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CATEGORY {
            get {
                return this.cATEGORYField;
            }
            set {
                this.cATEGORYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_PI_XML_DATA_MF {
        
        private string bINField;
        
        private string pERIOD_KEYField;
        
        private string a_F_S2_TYPE_RETURNField;
        
        private string a_F_S2_ANY_ACTIVITIESField;
        
        private string a_F_S2_SUBMISSION_DATField;
        
        private string a_F_S5_PAYMENT_NOT_BANKING_AMTField;
        
        private string a_F_S5_ISSUANCE_DEBIT_AMTField;
        
        private string a_F_S5_OTHER_ADJUST_AMTField;
        
        private string a_F_S6_ISSUANCE_CREDIT_AMTField;
        
        private string a_F_S6_OTHER_ADJUST_AMTField;
        
        private string a_F_S7_SD_AGAINST_DEBIT_NOTEField;
        
        private string a_F_S7_SD_AGAINST_CREDIT_NOTEField;
        
        private string a_F_S7_SD_AGAINST_EXPORTField;
        
        private string a_F_S7_FINE_PENALTY_OTHERField;
        
        private string a_F_S7_EXCISE_DUTYField;
        
        private string a_F_S7_DEVELOP_SURCHARGEField;
        
        private string a_F_S7_ICT_DEVELOP_SURCHARGEField;
        
        private string a_F_S7_HEALTH_CARE_SURCHARGEField;
        
        private string a_F_S7_ENV_PROTECT_SURCHARGEField;
        
        private string a_F_S7_CB_LAST_TP_VATField;
        
        private string a_F_S7_CB_LAST_TP_SDField;
        
        private string a_F_S11_REFUND_VATField;
        
        private string a_F_S11_REFUND_SDField;
        
        private string a_F_S10_REFUNDField;
        
        private string a_F_S10_NAMEField;
        
        private string a_F_S10_DESIGNATIONField;
        
        private string a_F_S10_MOBILEField;
        
        private string a_F_S10_NID_PPField;
        
        private string a_F_S10_EMAILField;
        
        private string a_F_S10_CONFIRMField;
        
        private string a_F_S7_INTEREST_OVERDUE_VATField;
        
        private string a_F_S7_INTEREST_OVERDUE_SDField;
        
        private string a_F_S7_FINE_PENALTYField;
        
        private string a_F_S5_OTHER_ADJUST_CMTField;
        
        private string a_F_S6_OTHER_ADJUST_CMTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIN {
            get {
                return this.bINField;
            }
            set {
                this.bINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIOD_KEY {
            get {
                return this.pERIOD_KEYField;
            }
            set {
                this.pERIOD_KEYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S2_TYPE_RETURN {
            get {
                return this.a_F_S2_TYPE_RETURNField;
            }
            set {
                this.a_F_S2_TYPE_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S2_ANY_ACTIVITIES {
            get {
                return this.a_F_S2_ANY_ACTIVITIESField;
            }
            set {
                this.a_F_S2_ANY_ACTIVITIESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S2_SUBMISSION_DAT {
            get {
                return this.a_F_S2_SUBMISSION_DATField;
            }
            set {
                this.a_F_S2_SUBMISSION_DATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S5_PAYMENT_NOT_BANKING_AMT {
            get {
                return this.a_F_S5_PAYMENT_NOT_BANKING_AMTField;
            }
            set {
                this.a_F_S5_PAYMENT_NOT_BANKING_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S5_ISSUANCE_DEBIT_AMT {
            get {
                return this.a_F_S5_ISSUANCE_DEBIT_AMTField;
            }
            set {
                this.a_F_S5_ISSUANCE_DEBIT_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S5_OTHER_ADJUST_AMT {
            get {
                return this.a_F_S5_OTHER_ADJUST_AMTField;
            }
            set {
                this.a_F_S5_OTHER_ADJUST_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S6_ISSUANCE_CREDIT_AMT {
            get {
                return this.a_F_S6_ISSUANCE_CREDIT_AMTField;
            }
            set {
                this.a_F_S6_ISSUANCE_CREDIT_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S6_OTHER_ADJUST_AMT {
            get {
                return this.a_F_S6_OTHER_ADJUST_AMTField;
            }
            set {
                this.a_F_S6_OTHER_ADJUST_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_SD_AGAINST_DEBIT_NOTE {
            get {
                return this.a_F_S7_SD_AGAINST_DEBIT_NOTEField;
            }
            set {
                this.a_F_S7_SD_AGAINST_DEBIT_NOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_SD_AGAINST_CREDIT_NOTE {
            get {
                return this.a_F_S7_SD_AGAINST_CREDIT_NOTEField;
            }
            set {
                this.a_F_S7_SD_AGAINST_CREDIT_NOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_SD_AGAINST_EXPORT {
            get {
                return this.a_F_S7_SD_AGAINST_EXPORTField;
            }
            set {
                this.a_F_S7_SD_AGAINST_EXPORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_FINE_PENALTY_OTHER {
            get {
                return this.a_F_S7_FINE_PENALTY_OTHERField;
            }
            set {
                this.a_F_S7_FINE_PENALTY_OTHERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_EXCISE_DUTY {
            get {
                return this.a_F_S7_EXCISE_DUTYField;
            }
            set {
                this.a_F_S7_EXCISE_DUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_DEVELOP_SURCHARGE {
            get {
                return this.a_F_S7_DEVELOP_SURCHARGEField;
            }
            set {
                this.a_F_S7_DEVELOP_SURCHARGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_ICT_DEVELOP_SURCHARGE {
            get {
                return this.a_F_S7_ICT_DEVELOP_SURCHARGEField;
            }
            set {
                this.a_F_S7_ICT_DEVELOP_SURCHARGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_HEALTH_CARE_SURCHARGE {
            get {
                return this.a_F_S7_HEALTH_CARE_SURCHARGEField;
            }
            set {
                this.a_F_S7_HEALTH_CARE_SURCHARGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_ENV_PROTECT_SURCHARGE {
            get {
                return this.a_F_S7_ENV_PROTECT_SURCHARGEField;
            }
            set {
                this.a_F_S7_ENV_PROTECT_SURCHARGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_CB_LAST_TP_VAT {
            get {
                return this.a_F_S7_CB_LAST_TP_VATField;
            }
            set {
                this.a_F_S7_CB_LAST_TP_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_CB_LAST_TP_SD {
            get {
                return this.a_F_S7_CB_LAST_TP_SDField;
            }
            set {
                this.a_F_S7_CB_LAST_TP_SDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S11_REFUND_VAT {
            get {
                return this.a_F_S11_REFUND_VATField;
            }
            set {
                this.a_F_S11_REFUND_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S11_REFUND_SD {
            get {
                return this.a_F_S11_REFUND_SDField;
            }
            set {
                this.a_F_S11_REFUND_SDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S10_REFUND {
            get {
                return this.a_F_S10_REFUNDField;
            }
            set {
                this.a_F_S10_REFUNDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S10_NAME {
            get {
                return this.a_F_S10_NAMEField;
            }
            set {
                this.a_F_S10_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S10_DESIGNATION {
            get {
                return this.a_F_S10_DESIGNATIONField;
            }
            set {
                this.a_F_S10_DESIGNATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S10_MOBILE {
            get {
                return this.a_F_S10_MOBILEField;
            }
            set {
                this.a_F_S10_MOBILEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S10_NID_PP {
            get {
                return this.a_F_S10_NID_PPField;
            }
            set {
                this.a_F_S10_NID_PPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S10_EMAIL {
            get {
                return this.a_F_S10_EMAILField;
            }
            set {
                this.a_F_S10_EMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S10_CONFIRM {
            get {
                return this.a_F_S10_CONFIRMField;
            }
            set {
                this.a_F_S10_CONFIRMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_INTEREST_OVERDUE_VAT {
            get {
                return this.a_F_S7_INTEREST_OVERDUE_VATField;
            }
            set {
                this.a_F_S7_INTEREST_OVERDUE_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_INTEREST_OVERDUE_SD {
            get {
                return this.a_F_S7_INTEREST_OVERDUE_SDField;
            }
            set {
                this.a_F_S7_INTEREST_OVERDUE_SDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S7_FINE_PENALTY {
            get {
                return this.a_F_S7_FINE_PENALTYField;
            }
            set {
                this.a_F_S7_FINE_PENALTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S5_OTHER_ADJUST_CMT {
            get {
                return this.a_F_S5_OTHER_ADJUST_CMTField;
            }
            set {
                this.a_F_S5_OTHER_ADJUST_CMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string A_F_S6_OTHER_ADJUST_CMT {
            get {
                return this.a_F_S6_OTHER_ADJUST_CMTField;
            }
            set {
                this.a_F_S6_OTHER_ADJUST_CMTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_MSG_REQ_91IT_SUBF_GOSERV {
        
        private DT_RET_TBF_GOSERV iTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_TBF_GOSERV ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_MSG_REQ_91IT_SUBF_VDS {
        
        private DT_RET_SUBF_VDS iTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_SUBF_VDS ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_MSG_REQ_91IT_SUBF_BOE {
        
        private DT_RET_SUBF_BOE iTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_SUBF_BOE ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_MSG_REQ_91IT_SUBF_CHALLAN {
        
        private DT_RET_SUBF_CHALLAN iTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_SUBF_CHALLAN ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_MSG_REQ_91IT_SUBF_ATTACH {
        
        private DT_RET_SUBF_ATTACH iTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_RET_SUBF_ATTACH ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nbr.gov.bd/regist91")]
    public partial class DT_RET_MSG_REQ_91ATTACH_DOCUMENT {
        
        private DT_ATTACH_DOCUMENT iTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_ATTACH_DOCUMENT ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SI_RET_SENDERCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591